# mesh3x3_uciePhysChannel_2stack.py
#
# Copyright (C) 2025-2026 Tactical Computing Laboratories, LLC
# All Rights Reserved
# contact@tactcomplabs.com
# See LICENSE in the top level directory for licensing details
#
# 3x3 mesh with num_stacks=2 UCIe PhysChannel links.
#
# merlin.test_nic and merlin.trafficgen both hardcode num_vns=1 when loading
# their networkIF subcomponent, making num_stacks=2 (which requires
# total_vns >= 2) impossible with those endpoints.  This test uses
# mordred.mordredTestEP, which takes num_vns as an explicit parameter and
# passes it to the networkIF subcomponent loader — enabling total_vns=2.
#
# With num_vns=2 in the router and endpoints, and uciePhysChannel configured
# as num_stacks=2 / num_vns_per_stack="1,1" (total_vns=2), all UCIe
# INIT/AGREE handshakes succeed and the multi-stack arbitration path in
# UCIeAdapterBase::trySend() is exercised through multi-hop routing.
#
# Traffic is generated by mordredTestEP: each endpoint sends num_messages
# messages, rotating through VN 0 and VN 1, to spread load across both stacks.
#

import sst
from sst import UnitAlgebra

testname = "mesh3x3_uciePhysChannel_2stack"

sst.setProgramOption("stop-at", "10us")

clk          = UnitAlgebra("1GHz")
clk_pd       = clk.invert()
link_latency = UnitAlgebra(0.8) * clk_pd
flit_size    = UnitAlgebra("16b")

num_vns = 2   # must match num_vns_per_stack sum and mordredTestEP num_vns

UCIeParams = {
    "link_latency"        : "2ns",
    "num_stacks"          : 2,          # two UCIe protocol stacks
    "num_vns_per_stack"   : "1,1",      # 1 VN per stack → total_vns=2 matches num_vns
    "credits_per_vn"      : "32",
    "flit_format"         : 5,
    "num_modules"         : 1,
    "num_lanes"           : 16,
    "lane_speed_gts"      : 32,
    "multi_protocol_mode" : "enhanced",
    "verbose"             : 1,
}

PortControlPCParams = {
    "flit_size"       : flit_size,
    "input_buf_size"  : UnitAlgebra(16) * flit_size,
    "output_buf_size" : UnitAlgebra(1)  * flit_size,
    "verbose"         : 0,
}

FixedRtrParams = {
    "verbose"         : 0,
    "clock"           : clk,
    "num_vcs"         : "1",
    "num_vns"         : str(num_vns),
    "flit_size"       : flit_size,
    "input_buf_size"  : UnitAlgebra(16) * flit_size,
    "output_buf_size" : UnitAlgebra(1)  * flit_size,
}

MordredNicPCParams = {
    "verbose"         : 0,
    "input_buf_size"  : "1kiB",
    "output_buf_size" : "1kiB",
}

links = dict()
def getLink(name1, name2):
    name = "link.%s_%s" % (name1, name2)
    if name not in links:
        links[name] = sst.Link(name)
    return links[name]

def wire_rtr_port(rtr, port_idx, port_name, link, ucie_ep_id):
    """Attach rtrPortControlPC + uciePhysChannel to one router port and connect the link."""
    pc = rtr.setSubComponent("portcontrol", "mordred.rtrPortControlPC", port_idx)
    pc.addParams(PortControlPCParams)
    ucie = pc.setSubComponent("port_iface", "prydwen.uciePhysChannel", 0)
    ucie.addParams(UCIeParams)
    ucie.addParams({"port_name": port_name, "endpoint_id": ucie_ep_id})
    rtr.addLink(link, port_name, link_latency)

def createMesh(x_size, y_size, local_ports):
    rtr_id = 0
    nports = 4 + local_ports
    rtr_params = {
        "num_ports"       : nports,
        "num_local_ports" : local_ports,
    }
    num_eps = x_size * y_size * local_ports
    for y in range(y_size):
        for x in range(x_size):
            rtr = sst.Component("rtr_%d_%d" % (x, y), "mordred.mordred_router")
            rtr.addParam("id", rtr_id)
            rtr.addParams(FixedRtrParams)
            rtr.addParams(rtr_params)
            rtr_topo = rtr.setSubComponent("topology", "mordred.MeshTopology")
            rtr_topo.addParams({"verbose": 0, "xDim": x_size, "yDim": y_size})

            if y != y_size - 1:
                wire_rtr_port(rtr, 0, "port0",
                    getLink("rtr_%d_%d" % (x, y), "rtr_%d_%d" % (x, y + 1)),
                    2000 + rtr_id * 10 + 0)
            if x != x_size - 1:
                wire_rtr_port(rtr, 1, "port1",
                    getLink("rtr_%d_%d" % (x, y), "rtr_%d_%d" % (x + 1, y)),
                    2000 + rtr_id * 10 + 1)
            if y != 0:
                wire_rtr_port(rtr, 2, "port2",
                    getLink("rtr_%d_%d" % (x, y - 1), "rtr_%d_%d" % (x, y)),
                    2000 + rtr_id * 10 + 2)
            if x != 0:
                wire_rtr_port(rtr, 3, "port3",
                    getLink("rtr_%d_%d" % (x - 1, y), "rtr_%d_%d" % (x, y)),
                    2000 + rtr_id * 10 + 3)

            for k in range(local_ports):
                port_idx  = 4 + k
                port_name = "port%d" % port_idx
                ep_name   = "ep_%d_%d_%d" % (x, y, k)
                ep_num    = (x * y_size * local_ports) + (y * local_ports) + k

                ep = sst.Component(ep_name, "mordred.mordredTestEP")
                ep.addParams({
                    "id"           : ep_num,
                    "num_peers"    : num_eps,
                    "num_vns"      : num_vns,
                    "num_messages" : 20,
                    "message_size" : UnitAlgebra(4) * flit_size,
                    "clock"        : clk,
                    "verbose"      : 0,
                })

                lnk = getLink("rtr_%d_%d" % (x, y), ep_name)
                wire_rtr_port(rtr, port_idx, port_name, lnk, 1000 + rtr_id * 10 + port_idx)

                ep_iface = ep.setSubComponent("networkIF", "mordred.mordredNicPC")
                ep_iface.addParams(MordredNicPCParams)
                ucie_ep = ep_iface.setSubComponent("port_iface", "prydwen.uciePhysChannel", 0)
                ucie_ep.addParams(UCIeParams)
                ucie_ep.addParams({"port_name": "port", "endpoint_id": ep_num})
                ep_iface.addLink(lnk, "port", link_latency)

            rtr_id += 1

local_ports = 1
x_size      = 3
y_size      = 3

createMesh(x_size, y_size, local_ports)

sst.setStatisticLoadLevel(7)
sst.setStatisticOutput("sst.statOutputCSV",
    {"filepath": "./stats.%s.csv" % testname, "separator": ", "})
sst.enableAllStatisticsForComponentType("prydwen.uciePhysChannel")

# EOF
